version: 2.0
jobs:
  test_build:
    machine:
      image: circleci/classic:201708-01

    CIRCLE_ARTIFACTS: /tmp/artifacts

    steps:
        - checkout
        - run: gem install fpm
        - run: sudo apt-get liblua5.2-0 install -y librpm3 librpmbuild3 librpmio3 librpmsign1 rpm2cpio debugedit rpm-common rpm
        - run: make build
        - run: make deb
        - run: make rpm
        - run: cp -R out ${CIRCLE_ARTIFACTS}
        - store_artifacts:
            path: /tmp/artifacts

  upload_packages:
    machine:
      enabled: true
    steps:
      - run: make package-upload

workflows:
  version: 2
  test_and_build:
    jobs:
      - test_build
      - upload_package:
          type: approval
          requires:
            - test_build
