version: 2.0
jobs:
  test_build:
    docker:
      - image: hostedgraphite/pythonbuild:2venv
      
    environment:
      CIRCLE_ARTIFACTS: /tmp/artifacts

    steps:
        - run: gem install fpm
        - run: sudo apt-get install rpm
        - run: make build
        - run: make deb
        - run: make rpm
        - run: cp -R out ${CIRCLE_ARTIFACTS}
        - store_artifacts:
            path: /tmp/artifacts

  upload_packages:
    machine:
      enabled: true
    steps:
      - run: make package-upload

workflows:
  version: 2
  test_and_build:
    jobs:
      - test_build
      - upload_package:
          type: approval
          requires:
            - test_build
