#! /bin/bash

### BEGIN INIT INFO
# Provides:          hg-agent
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Hosted Graphite agent
# Description: Hosted Graphite agent
### END INIT INFO

DESC="Hosted Graphite agent"
CHDIR="/var/opt/hg-agent"
DAEMON="/opt/hg-agent/bin/supervisord"
CTRL="/opt/hg-agent/bin/supervisorctl"
CFG="--configuration /etc/opt/hg-agent/supervisor.conf"

## Check to see if we are running as root first.
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root"
    exit 1
fi

eval CHDIR=$CHDIR

do_start() {
  CMD="$DAEMON $CFG"
  $CMD
}

do_stop() {
  STOP="$CTRL $CFG stop all"
  SHUTDOWN="$CTRL $CFG shutdown"
  $STOP && $SHUTDOWN
}

do_status() {
  STATUS="$CTRL $CFG status"
  echo "$DESC processes:"
  $STATUS
}

case "$1" in
  start)
    echo "Starting $DESC processes."
    do_start
    echo "$DESC started."
    ;;
  stop)
    echo "Stopping $DESC processes:"
    do_stop
    echo "$DESC stopped."
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    do_status
    ;;
  *)
    echo "Usage: sudo service hg-agent {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
